### ISSUE TITLE
RPA 开发与应用 发行了没有？没有找到啊。

### ISSUE THREAD

**Issue by vicrzchen** [allenlooplee/RPABook#2]
《RPA 开发与应用》想找来看看，没有找到。

OCR和NLP回事RPA在财务领域外的关键技术，如果只是拿来用，门槛其实不是太高。从Allen其他项目来看，已经把OCR应用降低到一个很低的门槛了。

**Comment by allenlooplee** [comment]
正在印刷，上市之后我就会贴出连接了。
