### ISSUE TITLE
《RPA开发与应用》126页 Extract InvoiceNum/InvoiceDate/AmountInFiguers的分配公式分别是什么？

### ISSUE THREAD

**Issue by GongChun** [allenlooplee/RPABook#3]
第一个分配按照书上图5-14下面一段的文字写入分配公式 InvoiceNum=item("word_result")("InvoiceNum").Vaule(Of system.UInt32)分配程序报错
![image](https://user-images.githubusercontent.com/84734644/119385620-f13ab580-bcf8-11eb-91f4-4580df7cdd0e.png)

InvoiceDate=item("words_result")("InvoiceDate").Value(Of String)
AmountInfiguers=item("words_result")("AmountInFiguers").Value(Of System.Double)
上面写的这两个分配怎么修改？
随书附带的Github的书上程序包已经由于活动组件的升级，没有办法打开程序Demo4的活动，如有看到，请回复一下，谢谢

**Comment by allenlooplee** [comment]
我刚刚照着书本的步骤徒手搞了一个项目，用最新的UiPath Studio Pro。你看看`For Each`活动的`Type Argument`属性现在是不是`Object`，如果是的话，你改为`Newtonsoft.Json.Linq.JObject`应该就可以了。

![image](https://user-images.githubusercontent.com/132692/120070540-9f5dab00-c0bd-11eb-8545-1ea9c3f05ff1.png)

原因是，`For Each`活动的`item`变量如果没有选择默认是`Object`类型，但`Results`集合中的元素实际上是`Newtonsoft.Json.Linq.JObject`类型，`Option Strict Off`的时候允许在声明类型为`Object`的`item`上使用`Newtonsoft.Json.Linq.JObject`的方法，`Option Strict On`的时候就必须把`item`变量设为正确的类型才能使用。我估计写书的时候UiPath使用`Option Strict Off`，现在使用`Option Strict On`。这样做的原因应该是防止类型不安全。

另外，如果你打算在正式的流程上用OCR，你可以看看[云可扩展OCR活动包](https://github.com/allenlooplee/CloudOcrActivitiesPack)。

**Comment by GongChun** [comment]
超级感谢，以为没人会回复我呢，经过提醒，确实可以了，！收到您的回复，我非常开心，这是我最近拜读您的大作，您的书是我买的RPA（UiPath）觉得最有水平的，更接近真实项目！



---原始邮件---
发件人: "Allen ***@***.***&gt;
发送时间: 2021年5月29日(周六) 晚上8:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [allenlooplee/RPABook] 《RPA开发与应用》126页 Extract InvoiceNum/InvoiceDate/AmountInFiguers的分配公式分别是什么？ (#3)




 
我刚刚照着书本的步骤徒手搞了一个项目，用最新的UiPath Studio Pro。你看看For Each活动的Type Argument属性现在是不是Object，如果是的话，你改为Newtonsoft.Json.Linq.JObject应该就可以了。

**Comment by allenlooplee** [comment]
不客气，看书的时候遇到别的问题也欢迎来这里探讨。
